# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-15 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20170709_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_title', models.CharField(max_length=100)),
                ('game_logo', models.FileField(upload_to='')),
            ],
        ),
    ]
